### ISSUE TITLE
Create a working Model Infrastructure

### ISSUE THREAD

**Issue by rschragger** [rschragger/Farmers-Market-Organiser#11]
Refer to #6 
Requires Sequelize tables for 

- [x] Events
- [x] Booking
- [x] Stalls
- [x] Stallholder
- [x] Products
- [x] User
   - [x] Contacts
   - [x] Role

Future possibilities (not required for MVP)

- Equipment Booking
- Equipment Stock
- Equipment

**Comment by rschragger** [comment]
- [x] Working on adding first model for 'user' and getting a response on api

**Comment by NancyMile** [comment]
Schema.sql proposed pushed to staging branch

**Comment by rschragger** [comment]
All base models as per diagram at https://app.diagrams.net/#G1D-auKNGSjG5zYR__J-e2U8asyyuv92FP are done
