### ISSUE TITLE
Model  for stallholder

### ISSUE THREAD

**Issue by NancyMile** [rschragger/Farmers-Market-Organiser#29]
Stallholder model created

**Comment by NancyMile** [comment]
The model has been pushed to the stage branch

**Comment by rschragger** [comment]
@NancyMile pull from staging, run `npm run seeds` and then `npm start` and check [http://localhost:3001/api/stallholder](http://localhost:3001/api/stallholder) 👍

**Comment by NancyMile** [comment]
Testing this on my local environment

**Comment by NancyMile** [comment]
Looks  good  it returned  some records

![Screen Shot 2022-08-29 at 8 59 31 pm](https://user-images.githubusercontent.com/6753416/187190158-f6f6b880-524a-4e6e-bc56-dbd93f4bc80d.png)

**Comment by NancyMile** [comment]
I am not  working on this  now
