### ISSUE TITLE
Model for Events

### ISSUE THREAD

**Issue by rschragger** [rschragger/Farmers-Market-Organiser#33]
refer to https://github.com/rschragger/Farmers-Market-Organiser/issues/11
Get Rough idea from https://app.diagrams.net/#G1D-auKNGSjG5zYR__J-e2U8asyyuv92FP

- [x]  Base model is done
- [x]  Foreign Key links have been established
- [x]  Data has been pulled from API
- [x]  Any linked data necessary has been recovered in API GET call

**Comment by rschragger** [comment]
Made model and seed data (procedural)

**Comment by NancyMile** [comment]
This one was in progress, I no longer working on this one
