### ISSUE TITLE
Model for Locations

### ISSUE THREAD

**Issue by rschragger** [rschragger/Farmers-Market-Organiser#34]
refer to https://github.com/rschragger/Farmers-Market-Organiser/issues/11
Get Rough idea from https://app.diagrams.net/#G1D-auKNGSjG5zYR__J-e2U8asyyuv92FP

- [x]  Base model is done
- [x]  Foreign Key links have been established
- [x]  Data has been pulled from API
- [x]  Any linked data necessary has been recovered in API GET call

**Comment by NancyMile** [comment]
Model location has been created  and pushed to stage branch

**Comment by NancyMile** [comment]
NO  longer  working  on this one.

**Comment by rschragger** [comment]
Done

**Comment by rschragger** [comment]
Adding a `logo_filename` field into Location model so we can access the images at `/public/images/logos/...`

as per ` <img src="/images/{{filename}}" alt="{{description}}">` from 14-MVC/01/11-Ins_Partials

**Comment by NancyMile** [comment]
An organiser can create a new location, done.
