### ISSUE TITLE
Model for User

### ISSUE THREAD

**Issue by rschragger** [rschragger/Farmers-Market-Organiser#36]
refer to https://github.com/rschragger/Farmers-Market-Organiser/issues/11
Combine contacts and role into User #31 
Get Rough idea from https://app.diagrams.net/#G1D-auKNGSjG5zYR__J-e2U8asyyuv92FP

- [x]  Base model is done
- [ ]  Foreign Key links have been established
   - [x] stallholder
   - [ ] location
- [x]  Data has been pulled from API
- [x]  Any linked data necessary has been recovered in API GET call
---
- [x] Add hooks
- [x] Add bcrypt hashing for password 
- [x] disallow password from being selected
- [x] role_type to auto fill in based on whether there is data in location_id or stallholder_id

**Comment by rschragger** [comment]
I'm not sure this needs to be 2 tables, please examine requirement

**Comment by SeanGenge** [comment]
When creating a user model, can you please add hooks and an instance method to check the password as well as encrypting the password. You can have a look at 20-stu-instance-method User Model

**Comment by rschragger** [comment]
- @SeanGenge I have left the password as minimum 6 characters. I have not made it alphanumeric etc (but we could in the future) 
- You cannot access the password in an API call but you can when looking at mysql on you local machine
- bcrypt hashing is working
- I think we will have `loginAsStallholder` and `loginAsOrganiser` variables and will use role_type to pick
- I allowed for a 'User' role_type just in case we need to test something further on, though I don't think it will be necessary. This validation will be good in case the web input doesn't match the validations or vice versa
- @RaviKVelaga role needs to be 'fed' in the signup form by which login is being used. We'll also need mandatory first_name, last_name etc - see Model `User`


Still have to add foreign keys, but Sean needs the auth to be working
Pull request #48
