### ISSUE TITLE
Create a Stall

### ISSUE THREAD

**Issue by rschragger** [rschragger/Farmers-Market-Organiser#78]
refer #30 , 

- [x] Create html form for new stall (`newStallForm.html`)
- [x] Link to `/api/stall` POST request

For PUT request, can we get user data, put it into above form as default values and then use this to PUT changes
- [x]  link GET and PUT requests to form

**Comment by NancyMile** [comment]
Stallget request working now. I will push the changes later

**Comment by NancyMile** [comment]
As  the  request  seem to  work  fine  now  for the stalll  now  I will be  working  on the html for addid , plisplay edit, deleteof stalls

**Comment by NancyMile** [comment]
display, edit  home routes.. working  fine ..  now  testing adding and deleting stalls
